#!/usr/bin/env zsh
set -fexo pipefail
# Depends: tigervnc-viewer
# ---------------
src_dir=${0:a:h}
vnc_address=127.0.0.1:5

(sleep 2 && vncviewer $vnc_address) &

args=(
    -vnc $vnc_address
    -vga virtio
    -device qemu-xhci
    -device usb-kbd
    -device usb-tablet
    # -audio pa,model=hda
)
$src_dir/run $args
